name: Test and publish
on:
  release:
    types:
      - published
env:
  SBT_OPTS: "-Xmx2G"
jobs:
  cleanup-previous-runs:
    name: Cleanup previous runs
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        env:
          GITHUB_TOKEN: "${{ secrets.RENKUBOT_GITHUB_TOKEN }}"
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [ cleanup-previous-runs ]
    steps:
      - uses: actions/checkout@v3
      - name: JDK set-up
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Unit test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean test
  examples:
    name: Run Examples
    runs-on: ubuntu-latest
    needs: [ cleanup-previous-runs ]
    steps:
      - uses: actions/checkout@v3
      - name: JDK set-up
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Run Examples
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean "Examples / test"
  formatter:
    name: Formatter
    runs-on: ubuntu-latest
    needs: [ cleanup-previous-runs ]
    steps:
      - uses: actions/checkout@v3
      - name: JDK set-up
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Formatter
        run: sbt scalafmtCheck
  publish:
    name: Publish
    runs-on: ubuntu-20.04 
    needs: [ unit-tests, formatter ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: JDK set-up
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Publish to Sonatype
        env:
          PGP_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.GPG_SIGNING_KEY_SONATYPE }}
          SONATYPE_USERNAME: travissdsc
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: sbt ci-release
