name: Test and publish
on:
  push:
    tags:
      - '*.*.*'
env:
  SBT_OPTS: "-XX:+CMSClassUnloadingEnabled -Xmx2G"
jobs:
  cleanup-previous-runs:
    name: Cleanup previous runs
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        env:
          GITHUB_TOKEN: "${{ secrets.RENKUBOT_GITHUB_TOKEN }}"
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [ cleanup-previous-runs ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Unit test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean test
  formatter:
    name: Formatter
    runs-on: ubuntu-latest
    needs: [ cleanup-previous-runs ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Formatter
        run: sbt scalafmtCheck
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ unit-tests, formatter ]
    env:
      DOCKER_LABEL: ${{ github.head_ref }}
      DOCKER_PUSH_LATEST: true
      DOCKER_REPOSITORY: renku/
      HELM_URL: https://storage.googleapis.com/kubernetes-helm
      HELM_TGZ: helm-v2.17.0-linux-amd64.tar.gz
    steps:
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY_SONATYPE" | base64 --decode | gpg --import
        env:
         GPG_SIGNING_KEY_SONATYPE: ${{ secrets.GPG_SIGNING_KEY_SONATYPE }}
      - name: Set up Sonatype credentials
        run: |
          echo -n 'credentials += Credentials(Path.userHome / ".sbt" / "sonatype_credentials")' >> ~/.sbt/1.0/sonatype.sbt
          echo 'realm=Sonatype Nexus Repository Manager
                host=s01.oss.sonatype.org
                user=travissdsc
                password='${{ secrets.SONATYPE_PASSWORD }} >> ~/.sbt/sonatype_credentials
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Write version to Chart.yaml
        run: |
          sudo rm -rf .git/index.lock
          sbt publishSigned
      - name: Set environment variables
        run: |
          echo "GIT_USER=Renku Bot" >> $GITHUB_ENV
          echo "GIT_EMAIL=renku@datascience.ch" >> $GITHUB_ENV
      - name: Build and push chart and images
        uses: SwissDataScienceCenter/renku-actions/publish-chart@v0.3.0
        env:
          CHART_PATH: helm-chart/renku-graph
          CHART_NAME: renku-graph
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Wait for chart to be available
        run: sleep 120
      - name: Update component version
        uses: SwissDataScienceCenter/renku-actions/update-component-version@v0.3.0
        env:
          CHART_NAME: renku-graph
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
