name: Test
on:
  push:
    branches:
      - main
      - 'hotfix-[0-9]+.[0-9]+**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
env:
  SBT_OPTS: "-Xmx2G"
jobs:
  cleanup-previous-runs:
    name: Cleanup previous runs
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        env:
          GITHUB_TOKEN: "${{ secrets.RENKUBOT_GITHUB_TOKEN }}"
  conventional-commits:
    name: Commit message check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: cleanup-previous-runs
    steps:
      - uses: actions/checkout@v3
      - name: JDK set-up
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Unit test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean test
  formatter:
    name: Formatter
    runs-on: ubuntu-latest
    needs: cleanup-previous-runs
    steps:
      - uses: actions/checkout@v3
      - name: JDK set-up
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Formatter
        run: sbt scalafmtCheck
